use hospitalmanagement;

USE Hospitalmanagement;

--1)Most consulted doctors
select d.doctorid,d.name as doctor_name,d.specialisation,COUNT(a.appointmentid) as total_consultations
from doctor d
join appointments a on d.doctorid=a.doctorid
group by d.doctorid,d.name,d.specialisation
group by total_consultations desc;


--2)Total revenue per month
select date_format(t.treatmentdate,'%Y-%m')as month,sum(t.cost)as total_revenue
from treatments t
group by date_format(t.treatmentdate, '%Y-%m')order by month;


--3)Most common diseases
select diagnosis,count(*) as total_cases from treatments
group by diagnosis order by total_cases desc;


--4)Patient visit frequency
select p.patientid, p.name as patient_name, count(a.appointmentid) as total_visits
from patient p join appointments a on p.patientid = a.patientid
group by p.patientid, p.name order by total_visits desc;


--5)Analyze doctor performance
select d.doctorid, d.name as doctor_name, d.specialisation, count(distinct a.patientid) as unique_patients_handled, count(a.appointmentid) as total_appointments
from doctor d
left join appointments a on d.doctorid = a.doctorid
group by d.doctorid, d.name, d.specialisation order by total_appointments desc;


--6)Average treatment cost by disease
select diagnosis,avg(cost) as average_treatment_cost
from treatments group by diagnosis
order by average_treatment_cost desc;


--7)Revenue generated by each patient
select p.patientid,p.name as patient_name,sum(t.cost) as total_spent
from patient p join treatments t on p.patientid = t.patientid
group by p.patientid, p.name order by total_spent desc;


--8) Number of appointments by specialization
select d.specialisation,count(a.appointmentid) as total_appointments
from doctor d join appointments a on d.doctorid = a.doctorid
group by d.specialisation order by total_appointments desc;


--9) Patients who visited more than once
select p.patientid, p.name as patient_name,count(a.appointmentid) as visit_count
from patient p
join appointments a on p.patientid = a.patientid
group by p.patientid, p.name having count(a.appointmentid) > 1 order by visit_count desc;


--10) Highest earning month
select  date_format(treatmentdate, '%Y-%m') as month,sum(cost) as revenue
from treatments group by date_format(treatmentdate, '%Y-%m')
order by revenue desc limit 1;